name: 'CI'
on:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install newman and test reporter
        run: npm install -g newman newman-reporter-xunit

      - name: Build docker image
        run: docker build --tag first-newman .

      - name: Run project
        run: docker run -d -p 5000:80 first-newman

      - name: Create directory to upload test results
        run: mkdir -p testArtifacts

      - name: Run newman tests
        run: newman run test/newman-testing/first-newman.postman_collection.json -e test/newman-testing/first-newman.postman_environment.json -r xunit --reporter-xunit-export testArtifacts/result.xml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: testArtifacts/result.xml

      - uses: dorny/test-reporter@v1
        name: Newman Tests
        if: always()
        with:
          path: testArtifacts/*.xml
          reporter: xunit
          fail-on-error: true

