name: Api testing
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install newman and test reporter
        run: npm install -g newman newman-reporter-html

      - name: Build docker image
        run: docker build --tag first-newman .

      - name: Run project
        run: docker run -d -p 5000:80 first-newman

      - name: Run newman tests
        run: newman run test/newman-testing/first-newman.postman_collection.json -e test/newman-testing/first-newman.postman_environment.json -r html

